var car1 = 'Toyota';
var car2 = 'Mercedes-Benz';
var car3 = 'BMW';
var car4 = 'Jaguar';
var car5 = 'Porsche';
console.log('Is car == Toyota? I predict True.');
console.log(car1 == 'Toyota');
console.log('Is car == Mercedes-Benz? I predict True.');
console.log(car2 == 'Mercedes-Benz');
console.log('Is car == BMW? I predict True.');
console.log(car3 == 'BMW');
console.log('Is car == Jaguar? I predict True.');
console.log(car4 == 'Jaguar');
console.log('Is car == Porsche? I predict True.');
console.log(car5 == 'Porsche');
console.log('\n');
console.log('Is car == Toyota? I predict false.');
console.log(car1 == 'Toyota1');
console.log('Is car == Mercedes-Benz? I predict false.');
console.log(car2 == 'Mercedes-Benz1');
console.log('Is car == BMW? I predict false.');
console.log(car3 == 'BMW1');
console.log('Is car == Jaguar? I predict false.');
console.log(car4 == 'Jaguar1');
console.log('Is car == Porsche? I predict false.');
console.log(car5 == 'Porsche1');
